[platformio]
default_envs = aura_cyd
src_dir = aura

[env:aura_cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter =
  +<*>
  -<pet_game.cpp>
  -<pet_storage.cpp>
  -<pet_ui.cpp>

lib_deps =
  bblanchon/ArduinoJson @ 7.4.1
  bodmer/TFT_eSPI @ 2.5.43
  tzapu/WiFiManager @ 2.0.17
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
  lvgl/lvgl @ 9.2.2

build_flags =
  -D USER_SETUP_LOADED
  -D LV_CONF_INCLUDE_SIMPLE
  -include "${PROJECT_DIR}/TFT_eSPI/User_Setup.h"
  -include "${PROJECT_DIR}/lvgl/src/lv_conf.h"
