[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Enable PSRAM (chip has 8MB embedded OPI PSRAM - allows mbedTLS to allocate from PSRAM heap)
board_build.arduino.memory_type = qio_opi

; Board-specific build flags
build_flags =
  -DCORE_DEBUG_LEVEL=2
  -DBOARD_HAS_PSRAM
  -DARDUINO_LOOP_STACK_SIZE=32768

; Partition scheme for larger apps with OTA support
board_build.partitions = partitions.csv

; Libraries
lib_deps =
  WiFiManager@>0.15
  ArduinoJson@>=6.18.0
  wasm3/wasm3
  ricmoo/QRCode@^0.0.1

; Monitor options
monitor_filters = esp32_exception_decoder

; Build optimization
build_type = release
